PROG= test

SRCS= test.c
CFLAGS+= -Wall -Wextra

MK_DEBUG_FILES= no
MAN=

.include <bsd.prog.mk>

.PHONY: testit
testit:	$(PROG)
	@./$(PROG) pledge || echo "PASS: Abort trap"
	LD_PRELOAD=$$(pwd)/libunsandbox.so ./$(PROG) pledge
	@./$(PROG) unveil || echo "PASS: No such file or directory"
	LD_PRELOAD=$$(pwd)/libunsandbox.so ./$(PROG) unveil
