PROG= test
SRCS= test.c

MK_DEBUG_FILES= no
MAN=
WARNS=	3

.include <bsd.prog.mk>

.PHONY: testit
testit:	$(PROG)
	./$(PROG) cap_enter || true
	LD_PRELOAD=$$(pwd)/libunsandbox.so ./$(PROG) cap_enter
	./$(PROG) cap_rights_limit || true
	LD_PRELOAD=$$(pwd)/libunsandbox.so ./$(PROG) cap_rights_limit
